#!/usr/bin/env python3
"""
One self-contained HTML audit report, for any checker.

Every static checker eventually wants the same page: a stat strip, a sticky
toolbar with a search box and severity chips, a list of units each carrying
its findings, and an optional notes panel at the bottom. Writing that page
once per checker means four near-identical copies of ~450 lines of CSS and JS,
which is how the copies quietly drift apart.

This module owns the page. A checker's report script converts its own result
dict into the neutral shape below and calls render_html(); it never touches
markup.

    from audit_report_html import Finding, Group, Stat, render_html

    render_html(
        out_path="reports/my_audit.html",
        title="Code rule audit",
        eyebrow="Acme · code_rule_checker",
        meta_html="Scanned <b>src/</b> · <b>42</b> units · rules v<b>1.0.0</b>",
        stats=[Stat("Units", 42), Stat("Clean", 30, tone="clean"),
               Stat("Errors", 3, tone="error")],
        groups=[Group(id="parser", sublabel="src/parser", counts={"error": 1},
                      findings=[Finding("error", "max-file-lines",
                                        "src/parser/Big.cs", "File is 812 lines")])],
        group_noun="unit",
        notes_title="2 rule(s) require manual review",
        notes=[("no-vendor-patching", "Needs the diff, not a snapshot.")],
        footer="Generated by scripts/my_report.py — re-run to refresh.",
    )

The page is a single file with no external requests: theme-aware (light, dark,
and an explicit data-theme override), responsive, and filterable offline.
"""
import json
from html import escape as html_escape
from pathlib import Path

SEVERITIES = ("error", "warning", "info")


class Stat:
    """One cell of the stat strip. tone tints the number: None, "clean",
    "error", "warning" or "info"."""

    def __init__(self, label, value, tone=None):
        self.label = label
        self.value = value
        self.tone = tone

    def as_dict(self):
        return {"label": self.label, "value": self.value, "tone": self.tone or ""}


class Finding:
    """One row inside a group. severity must be one of SEVERITIES; label is
    the rule id or check name; location is a file path (with :line already
    appended if there is one)."""

    def __init__(self, severity, label, location, message):
        if severity not in SEVERITIES:
            raise ValueError(f"severity must be one of {SEVERITIES}, got {severity!r}")
        self.severity = severity
        self.label = label
        self.location = location
        self.message = message

    def as_dict(self):
        return {"severity": self.severity, "label": self.label,
                "location": self.location or "", "message": self.message}


class Group:
    """One unit of the report — a module, package, file, test, whatever the
    checker's unit of work is. counts is {severity: n}; anything missing is 0.
    'clean' defaults to "no error and no warning findings"."""

    def __init__(self, id, sublabel="", findings=None, counts=None, clean=None):
        self.id = id
        self.sublabel = sublabel
        self.findings = list(findings or [])
        self.counts = {s: (counts or {}).get(s, 0) for s in SEVERITIES}
        if counts is None:
            for f in self.findings:
                self.counts[f.severity] += 1
        self.clean = (self.counts["error"] == 0 and self.counts["warning"] == 0) if clean is None else clean

    def as_dict(self):
        return {"id": self.id, "sublabel": self.sublabel, "clean": self.clean,
                "counts": self.counts, "findings": [f.as_dict() for f in self.findings]}


def render_html(out_path, title, eyebrow, meta_html, stats, groups,
                group_noun="unit", notes_title="", notes=None, footer=""):
    """Writes the report and returns its Path. 'notes' is a list of
    (label, text) pairs for the bottom panel — use it for checks that could
    not be automated, or for anything that isn't a per-unit finding. The panel
    hides itself when the list is empty."""
    payload = {
        "title": title,
        "eyebrow": eyebrow,
        "metaHtml": meta_html,
        "groupNoun": group_noun,
        "groupNounPlural": group_noun + "s",
        "stats": [s.as_dict() for s in stats],
        "groups": [g.as_dict() for g in groups],
        "notesTitle": notes_title,
        "notes": [{"label": label, "text": text} for label, text in (notes or [])],
        "footer": footer,
    }
    # </script> inside any string would close the data block early.
    data = json.dumps(payload).replace("</", "<\\/")
    # The <title> tag is filled in statically as well as by the script: some
    # readers (an artifact host, a tab title before JS runs) only see the tag.
    page = (_TEMPLATE
            .replace("__TITLE_PLACEHOLDER__", html_escape(title))
            .replace("__REPORT_DATA__", data))
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(page, encoding="utf-8")
    return out_path


_TEMPLATE = r"""<title>__TITLE_PLACEHOLDER__</title>
<style>
  :root {
    --paper: #f1f4f3;
    --paper-raised: #ffffff;
    --ink: #171d1f;
    --ink-soft: #4c5759;
    --line: #d7dedb;
    --accent: #1f6f78;
    --accent-soft: #e0eeec;
    --error: #9c3f2d;
    --error-soft: #f6e5df;
    --warning: #7d5a0c;
    --warning-soft: #f3ead3;
    --info: #3a4c93;
    --info-soft: #e5e8f6;
    --clean: #2e7048;
    --clean-soft: #e2efe4;
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --paper: #12171a;
      --paper-raised: #171e22;
      --ink: #e8edec;
      --ink-soft: #a9b6b8;
      --line: #2b3538;
      --accent: #5fd0c8;
      --accent-soft: #142d2b;
      --error: #ea9078;
      --error-soft: #2c1c16;
      --warning: #e0b25c;
      --warning-soft: #2c2411;
      --info: #a3b1f2;
      --info-soft: #1b2038;
      --clean: #7ed4a0;
      --clean-soft: #16281c;
    }
  }

  :root[data-theme="dark"] {
    --paper: #12171a;
    --paper-raised: #171e22;
    --ink: #e8edec;
    --ink-soft: #a9b6b8;
    --line: #2b3538;
    --accent: #5fd0c8;
    --accent-soft: #142d2b;
    --error: #ea9078;
    --error-soft: #2c1c16;
    --warning: #e0b25c;
    --warning-soft: #2c2411;
    --info: #a3b1f2;
    --info-soft: #1b2038;
    --clean: #7ed4a0;
    --clean-soft: #16281c;
  }

  * { box-sizing: border-box; }

  html, body { margin: 0; background: var(--paper); color: var(--ink); }

  body {
    font-family: ui-serif, "Iowan Old Style", "Palatino Linotype", Georgia, serif;
    line-height: 1.5;
    -webkit-font-smoothing: antialiased;
  }

  @media (prefers-reduced-motion: no-preference) {
    .group { transition: background-color 120ms ease; }
    .chip { transition: transform 100ms ease, background-color 120ms ease; }
  }

  .page { max-width: 900px; margin: 0 auto; padding: 2.75rem 1.5rem 5rem; }

  .eyebrow {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    font-size: 0.72rem;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--accent);
    margin: 0 0 0.6rem;
  }

  h1 {
    font-size: clamp(1.7rem, 1.3rem + 1.4vw, 2.35rem);
    font-weight: 600;
    margin: 0 0 0.5rem;
    text-wrap: balance;
    letter-spacing: -0.01em;
  }

  .meta {
    font-family: ui-monospace, "SF Mono", "Cascadia Code", "Roboto Mono", Menlo, Consolas, monospace;
    font-size: 0.85rem;
    color: var(--ink-soft);
    margin: 0;
  }

  .meta b { color: var(--ink); font-weight: 600; }

  .stats {
    margin-top: 2rem;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(105px, 1fr));
    gap: 1px;
    background: var(--line);
    border: 1px solid var(--line);
    border-radius: 6px;
    overflow: hidden;
  }

  .stat {
    background: var(--paper-raised);
    padding: 0.9rem 0.75rem;
    display: flex;
    flex-direction: column;
    gap: 0.2rem;
  }

  .stat-value {
    font-family: ui-monospace, "SF Mono", "Cascadia Code", "Roboto Mono", Menlo, Consolas, monospace;
    font-variant-numeric: tabular-nums;
    font-size: 1.5rem;
    font-weight: 600;
    line-height: 1;
  }

  .stat-label {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    font-size: 0.68rem;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    color: var(--ink-soft);
  }

  .stat-clean .stat-value { color: var(--clean); }
  .stat-error .stat-value { color: var(--error); }
  .stat-warning .stat-value { color: var(--warning); }
  .stat-info .stat-value { color: var(--info); }

  .toolbar {
    position: sticky;
    top: 0;
    z-index: 5;
    margin: 1.75rem -1.5rem 0;
    padding: 0.85rem 1.5rem;
    background: color-mix(in srgb, var(--paper) 88%, transparent);
    backdrop-filter: blur(8px);
    -webkit-backdrop-filter: blur(8px);
    border-bottom: 1px solid var(--line);
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.6rem 0.85rem;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }

  #search {
    flex: 1 1 220px;
    min-width: 180px;
    font-family: inherit;
    font-size: 0.85rem;
    padding: 0.5rem 0.7rem;
    border: 1px solid var(--line);
    border-radius: 5px;
    background: var(--paper-raised);
    color: var(--ink);
  }

  #search:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }

  .chips { display: flex; flex-wrap: wrap; gap: 0.4rem; }

  .chip {
    font-family: inherit;
    font-size: 0.72rem;
    font-weight: 600;
    letter-spacing: 0.02em;
    border: 1px solid var(--line);
    background: var(--paper-raised);
    color: var(--ink-soft);
    padding: 0.32rem 0.65rem 0.32rem 0.55rem;
    border-radius: 999px;
    cursor: pointer;
    display: inline-flex;
    align-items: center;
    gap: 0.35rem;
  }

  .chip:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
  .chip .dot { width: 0.5rem; height: 0.5rem; border-radius: 50%; background: currentColor; opacity: 0.55; }

  .chip[data-filter="error"] { color: var(--error); }
  .chip[data-filter="warning"] { color: var(--warning); }
  .chip[data-filter="info"] { color: var(--info); }

  .chip.active { transform: translateY(-1px); border-color: transparent; }
  .chip.active[data-filter="error"] { background: var(--error); color: var(--paper-raised); }
  .chip.active[data-filter="warning"] { background: var(--warning); color: var(--paper-raised); }
  .chip.active[data-filter="info"] { background: var(--info); color: var(--paper-raised); }
  .chip.active .dot { background: var(--paper-raised); opacity: 1; }

  .show-clean {
    font-size: 0.78rem;
    color: var(--ink-soft);
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    margin-left: auto;
    white-space: nowrap;
  }

  .show-clean input { accent-color: var(--accent); }

  #result-count { width: 100%; font-size: 0.72rem; color: var(--ink-soft); order: 5; }

  .group-list { list-style: none; margin: 0; padding: 0; }

  .group { padding: 0.95rem 0; border-bottom: 1px solid var(--line); }
  .group[hidden] { display: none; }

  .group-head { display: flex; align-items: baseline; flex-wrap: wrap; gap: 0.15rem 0.65rem; }

  .group-id {
    font-family: ui-monospace, "SF Mono", "Cascadia Code", "Roboto Mono", Menlo, Consolas, monospace;
    font-size: 0.98rem;
    font-weight: 600;
  }

  .group-sublabel {
    font-family: ui-monospace, "SF Mono", "Cascadia Code", "Roboto Mono", Menlo, Consolas, monospace;
    font-size: 0.78rem;
    color: var(--ink-soft);
  }

  .group-summary { margin-left: auto; display: flex; flex-wrap: wrap; gap: 0.35rem; }

  .pill {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    font-size: 0.68rem;
    font-weight: 700;
    letter-spacing: 0.02em;
    padding: 0.1rem 0.45rem;
    border-radius: 999px;
    font-variant-numeric: tabular-nums;
  }

  .pill-error { background: var(--error-soft); color: var(--error); }
  .pill-warning { background: var(--warning-soft); color: var(--warning); }
  .pill-info { background: var(--info-soft); color: var(--info); }
  .pill-clean { background: var(--clean-soft); color: var(--clean); }

  .group-body { margin-top: 0.55rem; display: flex; flex-direction: column; gap: 0.3rem; }

  .finding {
    border-left: 3px solid transparent;
    padding: 0.35rem 0 0.35rem 0.7rem;
    font-size: 0.86rem;
  }

  .finding-error { border-color: var(--error); background: var(--error-soft); }
  .finding-warning { border-color: var(--warning); background: var(--warning-soft); }
  .finding-info { border-color: var(--info); background: var(--info-soft); }

  .finding .label {
    font-family: ui-monospace, "SF Mono", "Cascadia Code", "Roboto Mono", Menlo, Consolas, monospace;
    font-weight: 600;
  }

  .finding .loc {
    font-family: ui-monospace, "SF Mono", "Cascadia Code", "Roboto Mono", Menlo, Consolas, monospace;
    font-size: 0.78rem;
    color: var(--ink-soft);
  }

  .finding .msg { display: block; margin-top: 0.1rem; }

  .group-clean .group-body { display: none; }

  #empty-state {
    padding: 2.5rem 0;
    text-align: center;
    color: var(--ink-soft);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    font-size: 0.85rem;
  }

  #empty-state[hidden] { display: none; }

  .notes {
    margin-top: 2.5rem;
    padding: 1rem 1.1rem;
    border: 1px solid var(--line);
    border-radius: 6px;
    background: var(--paper-raised);
  }

  .notes h2 { font-size: 0.95rem; margin: 0 0 0.6rem; }
  .notes ul { margin: 0; padding-left: 1.1rem; }
  .notes li { font-size: 0.84rem; margin: 0.3rem 0; }
  .notes .label {
    font-family: ui-monospace, "SF Mono", "Cascadia Code", "Roboto Mono", Menlo, Consolas, monospace;
    font-weight: 600;
  }

  footer {
    margin-top: 2.5rem;
    padding-top: 1rem;
    border-top: 1px solid var(--line);
    font-family: ui-monospace, "SF Mono", "Cascadia Code", "Roboto Mono", Menlo, Consolas, monospace;
    font-size: 0.75rem;
    color: var(--ink-soft);
  }

  @media (max-width: 640px) {
    .stats { grid-template-columns: repeat(2, 1fr); }
    .toolbar { margin-inline: -1rem; padding-inline: 1rem; }
    .show-clean { margin-left: 0; }
  }
</style>

<div class="page">
  <p class="eyebrow" id="eyebrow"></p>
  <h1 id="title"></h1>
  <p class="meta" id="meta"></p>

  <div class="stats" id="stats"></div>

  <div class="toolbar">
    <input type="search" id="search" placeholder="Filter&hellip;" aria-label="Filter results">
    <div class="chips" role="group" aria-label="Severity filters">
      <button class="chip" data-filter="error"><span class="dot"></span>Error</button>
      <button class="chip" data-filter="warning"><span class="dot"></span>Warning</button>
      <button class="chip" data-filter="info"><span class="dot"></span>Info</button>
    </div>
    <label class="show-clean"><input type="checkbox" id="show-clean">Show clean</label>
    <p id="result-count"></p>
  </div>

  <ol class="group-list" id="group-list"></ol>
  <p id="empty-state" hidden>Nothing matches this filter.</p>

  <div class="notes" id="notes"></div>

  <footer id="footer"></footer>
</div>

<script type="application/json" id="report-data">
__REPORT_DATA__
</script>

<script>
(function () {
  var data = JSON.parse(document.getElementById('report-data').textContent);

  function esc(s) {
    var d = document.createElement('div');
    d.textContent = s == null ? '' : s;
    return d.innerHTML;
  }

  document.title = data.title;
  document.getElementById('title').textContent = data.title;
  document.getElementById('eyebrow').textContent = data.eyebrow;
  // metaHtml is authored by the checker, not by user input — inline markup
  // (<b>, &middot;) is the point of the field.
  document.getElementById('meta').innerHTML = data.metaHtml;
  document.getElementById('footer').textContent = data.footer;
  document.getElementById('search').placeholder =
    'Filter by ' + data.groupNoun + ', rule, file or message…';

  var statsEl = document.getElementById('stats');
  data.stats.forEach(function (s) {
    var d = document.createElement('div');
    d.className = 'stat' + (s.tone ? ' stat-' + s.tone : '');
    d.innerHTML = '<span class="stat-value">' + esc(s.value) + '</span>' +
                  '<span class="stat-label">' + esc(s.label) + '</span>';
    statsEl.appendChild(d);
  });

  var listEl = document.getElementById('group-list');
  var emptyEl = document.getElementById('empty-state');
  var resultCountEl = document.getElementById('result-count');
  var searchEl = document.getElementById('search');
  var showCleanEl = document.getElementById('show-clean');
  var chips = Array.prototype.slice.call(document.querySelectorAll('.chip'));
  var activeFilters = new Set();

  function searchText(g) {
    var parts = [g.id, g.sublabel];
    g.findings.forEach(function (f) { parts.push(f.label, f.location, f.message); });
    return parts.join(' ').toLowerCase();
  }

  function buildLi(g) {
    var li = document.createElement('li');
    li.className = 'group' + (g.findings.length === 0 ? ' group-clean' : '');
    li.dataset.clean = g.findings.length === 0 ? 'true' : 'false';
    var severities = {};
    g.findings.forEach(function (f) { severities[f.severity] = true; });
    li.dataset.severities = Object.keys(severities).join(' ');
    li._search = searchText(g);

    var pills = '';
    if (g.clean) pills += '<span class="pill pill-clean">clean</span>';
    ['error', 'warning', 'info'].forEach(function (s) {
      if (g.counts[s]) pills += '<span class="pill pill-' + s + '">' + g.counts[s] + ' ' + s + '</span>';
    });

    var body = '';
    g.findings.forEach(function (f) {
      body += '<div class="finding finding-' + f.severity + '">' +
        '<span class="label">' + esc(f.label) + '</span>' +
        (f.location ? ' &middot; <span class="loc">' + esc(f.location) + '</span>' : '') +
        '<span class="msg">' + esc(f.message) + '</span></div>';
    });

    li.innerHTML =
      '<div class="group-head">' +
        '<span class="group-id">' + esc(g.id) + '</span>' +
        '<span class="group-sublabel">' + esc(g.sublabel) + '</span>' +
        '<span class="group-summary">' + pills + '</span>' +
      '</div>' +
      '<div class="group-body">' + body + '</div>';

    return li;
  }

  var fragment = document.createDocumentFragment();
  data.groups.forEach(function (g) { fragment.appendChild(buildLi(g)); });
  listEl.appendChild(fragment);

  var allLis = Array.prototype.slice.call(listEl.children);

  function applyFilters() {
    var q = searchEl.value.trim().toLowerCase();
    var showClean = showCleanEl.checked;
    var visible = 0;

    allLis.forEach(function (li) {
      if (li.dataset.clean === 'true' && !showClean) { li.hidden = true; return; }
      var severities = li.dataset.severities ? li.dataset.severities.split(' ') : [];
      var sevOk = activeFilters.size === 0 || severities.some(function (s) { return activeFilters.has(s); });
      var show = sevOk && (!q || li._search.indexOf(q) !== -1);
      li.hidden = !show;
      if (show) visible++;
    });

    emptyEl.hidden = visible !== 0;
    var total = allLis.length;
    var noun = total === 1 ? data.groupNoun : data.groupNounPlural;
    resultCountEl.textContent = visible === total
      ? total + ' ' + noun
      : visible + ' of ' + total + ' ' + data.groupNounPlural;
  }

  chips.forEach(function (chip) {
    chip.addEventListener('click', function () {
      var f = chip.dataset.filter;
      if (activeFilters.has(f)) { activeFilters.delete(f); chip.classList.remove('active'); }
      else { activeFilters.add(f); chip.classList.add('active'); }
      applyFilters();
    });
  });

  searchEl.addEventListener('input', applyFilters);
  showCleanEl.addEventListener('change', applyFilters);
  applyFilters();

  var notesEl = document.getElementById('notes');
  if (data.notes && data.notes.length) {
    var html = '<h2>' + esc(data.notesTitle || 'Notes') + '</h2><ul>';
    data.notes.forEach(function (n) {
      html += '<li><span class="label">' + esc(n.label) + '</span> &mdash; ' + esc(n.text) + '</li>';
    });
    notesEl.innerHTML = html + '</ul>';
  } else {
    notesEl.hidden = true;
  }
})();
</script>
"""
