#!/usr/bin/env python3
"""
Renders code_rule_checker results as console text and as a self-contained HTML
report. The page itself comes from audit_report_html.py, shared with every
other checker in this kit — this file only maps one checker's result dict onto
the neutral report shape.

Usage:
  ./code_rule_report.py                 # text + write the HTML report
  ./code_rule_report.py --text          # text only
  ./code_rule_report.py --html          # write the HTML report only
  ./code_rule_report.py --json          # raw JSON
  ./code_rule_report.py --out PATH      # HTML somewhere other than the default
  ./code_rule_report.py --rules PATH    # non-default rules file
"""
import json
import sys
from pathlib import Path

from audit_report_html import Finding, Group, Stat, render_html
from code_rule_checker import DEFAULT_RULES_PATH, check_all

DEFAULT_HTML_PATH = Path(__file__).resolve().parent.parent / "reports" / "code_rule_audit.html"


def render_text(report):
    summary = report["summary"]
    print(f"Code rule audit across {report['total']} unit(s) (rules v{report['rulesVersion']})\n")

    for r in report["units"]:
        if not r["findings"]:
            continue
        print(f"=== {r['id']} ({r['path']}) — "
              f"{r['counts']['error']} error(s), {r['counts']['warning']} warning(s), "
              f"{r['counts']['info']} info ===")
        for f in r["findings"]:
            loc = f["file"] + (f":{f['line']}" if f["line"] else "")
            print(f"  [{f['severity'].upper():<7}] {f['rule']:<40} {loc}")
            print(f"            {f['message']}")
        print()

    print("=" * 67)
    print(f"Summary: {report['total']} unit(s) — {summary['clean']} clean, {summary['flagged']} flagged")
    print(f"Findings: {summary['bySeverity']['error']} error, "
          f"{summary['bySeverity']['warning']} warning, {summary['bySeverity']['info']} info")
    if report["manualRules"]:
        print(f"\n{len(report['manualRules'])} rule(s) require manual review (not automated):")
        for r in report["manualRules"]:
            print(f"  - {r['id']}")


def write_html_report(report, out_path=DEFAULT_HTML_PATH, rules_path=None):
    summary = report["summary"]
    rules_name = Path(rules_path or DEFAULT_RULES_PATH).name

    groups = [
        Group(
            id=u["id"],
            sublabel=u["path"],
            counts=u["counts"],
            clean=u["clean"],
            findings=[
                Finding(f["severity"], f["rule"],
                        f["file"] + (f":{f['line']}" if f["line"] else ""),
                        f["message"])
                for f in u["findings"]
            ],
        )
        for u in report["units"]
    ]

    stats = [
        Stat("Units", report["total"]),
        Stat("Clean", summary["clean"], tone="clean"),
        Stat("Flagged", summary["flagged"], tone="error"),
        Stat("Errors", summary["bySeverity"]["error"], tone="error"),
        Stat("Warnings", summary["bySeverity"]["warning"], tone="warning"),
        Stat("Info", summary["bySeverity"]["info"], tone="info"),
    ]

    return render_html(
        out_path=out_path,
        title="Code rule audit",
        eyebrow="code_rule_checker",
        meta_html=(f"<b>{report['total']}</b> units &middot; rules v<b>{report['rulesVersion']}</b> "
                   f"from <b>{rules_name}</b> &middot; vendored files auto-excluded"),
        stats=stats,
        groups=groups,
        group_noun="unit",
        notes_title=f"{len(report['manualRules'])} rule(s) require manual review (not automated)",
        notes=[(r["id"], r["description"]) for r in report["manualRules"]],
        footer="Generated by scripts/code_rule_report.py — re-run to refresh this file.",
    )


def main():
    args = sys.argv[1:]
    rules_path = None
    out_path = DEFAULT_HTML_PATH
    if "--rules" in args:
        rules_path = args[args.index("--rules") + 1]
    if "--out" in args:
        out_path = args[args.index("--out") + 1]

    report = check_all(rules_path)

    if "--json" in args:
        print(json.dumps(report, indent=2))
        return

    if "--html" not in args:
        render_text(report)

    if "--text" not in args:
        written = write_html_report(report, out_path, rules_path)
        print(f"\nHTML report: {written}")


if __name__ == "__main__":
    main()
